name: DockerBuild AMD64

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version patch"
        required: true
        default: "8.4.11"

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export PHP AMD64
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --target export \
            --build-arg VERSION=${{ github.event.inputs.version }} \
            -o type=tar,dest=php-${{ github.event.inputs.version }}-amd64.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-${{ github.event.inputs.version }}-amd64-tarball
          path: php-${{ github.event.inputs.version }}-amd64.tar
